In [3]:
import numpy as np

# Define two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Perform matrix multiplication
C = np.dot(A, B)  # Alternatively, use A @ B
C2 = A @ B

# Print the result
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix C (Result of A * B):")
print(C)

print("\nMatrix C2 (Result of A * B):")
print(C2)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix C (Result of A * B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix C2 (Result of A * B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
